version: "3.7"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.compose
    environment:
      - NBUSER=leslie
    ports: 
      - "8888:8888"
    volumes:
      - .:/home/leslie:delegated
